/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIQytetet;
/**
 *
 * @author juliu
 */
import modeloqytetet.Qytetet;
public class VistaQytetet extends javax.swing.JPanel {

    /**
     * Creates new form VistaQytetet
     */
    public VistaQytetet() {
        initComponents();
    }

    public void actualizarQytetet(Qytetet qytetet){
        this.vistaJugador1.actualizarJugador(qytetet.getJugadorActual().toString());
        this.vistaCasilla1.actualizar(qytetet.getJugadorActual().getCasillaActual().toString());
        if (qytetet.getCartaActual() != null){
            this.vistaSorpresa1.actualizarSorpresa(qytetet.getCartaActual().toString());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vistaCasilla1 = new GUIQytetet.VistaCasilla();
        vistaJugador1 = new GUIQytetet.VistaJugador();
        vistaSorpresa1 = new GUIQytetet.VistaSorpresa();

        vistaCasilla1.setBackground(new java.awt.Color(0, 0, 204));
        vistaCasilla1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info Casilla", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 51, 0))); // NOI18N
        vistaCasilla1.setForeground(new java.awt.Color(255, 51, 0));

        vistaJugador1.setBackground(new java.awt.Color(0, 255, 0));
        vistaJugador1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info Jugador", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        vistaJugador1.setForeground(new java.awt.Color(51, 51, 255));
        vistaJugador1.setToolTipText("Jugador");

        vistaSorpresa1.setBackground(new java.awt.Color(255, 0, 51));
        vistaSorpresa1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ultima Carta Sorpresa", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 153, 0))); // NOI18N
        vistaSorpresa1.setForeground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vistaSorpresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vistaCasilla1, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(vistaJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vistaJugador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vistaCasilla1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vistaSorpresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUIQytetet.VistaCasilla vistaCasilla1;
    private GUIQytetet.VistaJugador vistaJugador1;
    private GUIQytetet.VistaSorpresa vistaSorpresa1;
    // End of variables declaration//GEN-END:variables
}